#!/bin/bash

exec 2>&1

echo "Config watcher started" 

export SVDIR=$XDG_CONFIG_HOME/runit/onXSession

./run-command-on-file-modify.sh $XDG_CONFIG_HOME/sxhkd/sxhkdrc "sv reload sxhkd" &

./run-command-on-file-modify.sh $XDG_CONFIG_HOME/polybar/config.ini "sv restart polybar" &

./run-command-on-file-modify.sh $XDG_CONFIG_HOME/bspwm/bspwmrc "bspc wm -r" &

./run-command-on-file-modify.sh $XDG_CONFIG_HOME/.Xresources "xrdb -merge $XDG_CONFIG_HOME/.Xresources" &

wait
