#!/bin/bash

exec 2>&1

echo "Sxhkd config watcher started" 
exec /home/sidharta/scripts/run-command-on-file-modify.sh $XDG_CONFIG_HOME/sxhkd/sxhkdrc "echo h > $XDG_CONFIG_HOME/runit/onXSession/sxhkd/supervise/control"
