#!/bin/bash

exec 2>&1

# Read config file
test -x ./config && . ./config

echo "$SERVICE_NAME started" 

cd $PLEX_HOME || exit 1
export PLEX_MEDIA_SERVER_HOME=$PLEX_HOME
export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=$PLEX_DATA
exec ./Plex\ Media\ Server
