#!/bin/bash

exec 2>&1

# Read config file
test -x ./config && . ./config

echo "$SERVICE_NAME started" 

cd /opt/plex/src/active/root/usr/lib/plexmediaserver || exit 1
export PLEX_MEDIA_SERVER_HOME=/opt/plex/src/active/root/usr/lib/plexmediaserver
export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/opt/plex/data
exec ./Plex\ Media\ Server
