#!/bin/bash

bspc wm -O eDP1 HDMI1
bspc monitor eDP1 --reset-desktops 1 2 3 4 5 6 7 8 9
bspc monitor HDMI1 --reset-desktops 1 2 3 4 5 6 7 8 9

~/.config/bspwm/scripts/monocle-no-padding.sh &

bspc config normal_border_color "#ff0f9b"
bspc config focused_border_color "#9b0fff"
bspc config presel_feedback_color "#ff0000"

bspc config border_width 3
bspc config window_gap 30
bspc config top_padding 0
bspc config -m eDP1 top_padding 10
# bspc config -m eDP1 top_monocle_padding 30

bspc rule --add "Peek" state=floating

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config swallow_first_click  true
# bspc config borderless_singleton true
bspc config single_monocle true
