#!/usr/bin/bash

sudo true

PROJECT_NAME=$(echo $PWD | rev | cut --delimiter=/ -f1 | rev)
VOID_DIR="/home/sidharta/.void-packages"
VOID_PACKAGE_DIR="$VOID_DIR/srcpkgs/$PROJECT_NAME"
VOID_PACKAGE_PATCH_DIR="$VOID_PACKAGE_DIR/patches"
PATCH_PATH="/tmp/git-patch.patch"


git diff origin/master > $PATCH_PATH

if [[ ! -d $VOID_PACKAGE_DIR ]]; then
	echo "Void package directory not found: $VOID_PACKAGE_DIR"
	exit -1
fi

if [[ ! -d $VOID_PACKAGE_PATCH_DIR ]]; then
	mkdir "$VOID_PACKAGE_PATCH_DIR"
fi

mv "$PATCH_PATH" "$VOID_PACKAGE_PATCH_DIR"
$VOID_DIR/xbps-src pkg $PROJECT_NAME
sudo xbps-install -fy $PROJECT_NAME
