#!/bin/bash

if [ "$EUID" = "0" ]; then
	RUNIT_DIR=/var/service/
else
	RUNIT_DIR=$XDG_CONFIG_HOME/runit
fi

 find "$RUNIT_DIR" -type l -printf "%p|%f\n" | while IFS="|" read file_path file_name; do
	SUPERVISE_DIR=$file_path/supervise
	PID=$(cat $SUPERVISE_DIR/pid)
	STAT=$(cat $SUPERVISE_DIR/stat)
	if test -n "$PID" && ! ps -p $PID > /dev/null; then
		PID="$PID*"
	fi
	echo -e "$PID\t$STAT\t$file_name"
done | column -s "$(echo -e "\t")" --table --table-columns "PID,STAT,NAME"
