#!/bin/bash

SERVICE_DIR=$XDG_CONFIG_HOME/runit/services/$1
SERVICE_SUPERVISE_DIR="$SERVICE_DIR/supervise"

if [[ -z "$1" ]]; then
	echo "You must provide a service name as argument"
	exit -1
fi

if [[ ! -d "$SERVICE_DIR" ]]; then
	echo "Service does not exist!"
	exit -1
fi

SERVICE_PID=$(cat $SERVICE_SUPERVISE_DIR/pid)

if [[ -z "$SERVICE_PID" ]]; then
	echo "Service is not running. Service stat is $(cat $SERVICE_SUPERVISE_DIR/stat)"
	exit -1
fi

LOG_FILE_PATH="$SERVICE_DIR/log/logfiles/current"

if [[ ! -r $LOG_FILE_PATH ]]; then
	echo "Not logs found for service"
	exit -1;
fi

tail $LOG_FILE_PATH -f
