#!/bin/bash

SERVICE_NAME=$1
SIGNAL_NAME=$2

case $SIGNAL_NAME in
	up)
		SIGNAL="u"
	;;
	down)
		SIGNAL="d"
	;;
	once)
		SIGNAL="o"
	;;
	pause)
		SIGNAL="p"
	;;
	continue)
		SIGNAL="c"
	;;
	hangup)
		SIGNAL="h"
	;;
	alarm)
		SIGNAL="a"
	;;
	interrupt)
		SIGNAL="i"
	;;
	quit)
		SIGNAL="q"
	;;
	user1)
		SIGNAL="1"
	;;
	user2)
		SIGNAL="2"
	;;
	terminate)
		SIGNAL="t"
	;;
	kill)
		SIGNAL="k"
	;;
	exit)
		SIGNAL="x"
	;;
	*)
		echo -e "Only supported options are: up down once pause continue hangup alarm interrupt quit user1 user2 terminate kill exit"
		exit -1
	;;
esac

if [ "$(id -u)" = "0" ]; then
	echo "Do not run this program as root."
	exit -1
fi

if [ -z "$SERVICE_NAME" ]; then
	echo "You must provide a service name the first argument"
	exit -1
fi

SERVICE_PATH=$XDG_CONFIG_HOME/runit/services/$SERVICE_NAME

if [[ ! -d "$SERVICE_PATH" ]]; then
	echo "Service does not exist, or is not a directory!"
	exit -1
fi

SERVICE_PID=$(test -r "$SERVICE_PATH/supervise/pid" && cat $SERVICE_PATH/supervise/pid)

if [[ -z "$SERVICE_PID" ]] && [[ ! $SIGNAL == "u" ]]; then
	echo "Service is not running."
	exit -1
fi

SERVICE_CONTROL=$SERVICE_PATH/supervise/control
if [[ ! -e $SERVICE_CONTROL ]]; then
	echo "Service control does not exist. Is it really running?"
fi

echo $SIGNAL > $SERVICE_CONTROL
